// A pasta services serve para configurar os serviços da aplicação como axios, history etc...

// Depois de instalar o history, importamos createBrowserHistory que serve para redirecionamento de paginas.
import { createBrowserHistory } from 'history'
// Chamando a função...
const history = createBrowserHistory()
// exportando a mesma...
export default history